import"./assets/styles-Dt4zwTEg.js";import{i as a,a as s}from"./assets/vendor-4yCzdkXl.js";function k(t,e,o){t.forEach(n=>{n.classList.remove(o)}),e.classList.add(o)}function B(t,e="success"){const o={message:t,position:"topRight",timeout:3e3};switch(e){case"success":a.success(o);break;case"error":a.error(o);break;case"warning":a.warning(o);break;case"info":a.info(o);break;default:a.error({message:"invalid type of toast",position:"topRight",timeout:3e3})}}const r={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalCloseButton:document.querySelector(".modal__close-btn"),modalProduct:document.querySelector(".modal-product"),searchForm:document.querySelector(".search-form"),searchFormClearButton:document.querySelector(".search-form__btn-clear"),AddToCartBtn:document.querySelector(".modal-product__btn--cart")};function R(){r.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden",document.addEventListener("keydown",S),r.modalCloseButton.addEventListener("click",b),r.modal.addEventListener("click",E)}function h(){r.modal.classList.remove("modal--is-open"),document.body.style.overflow="",document.removeEventListener("keydown",S),r.modalCloseButton.removeEventListener("click",b),r.modal.removeEventListener("click",E)}function S(t){console.log(t.code),t.code==="Escape"&&h()}function b(){h()}function E(t){t.target===r.modal&&h()}const A="https://dummyjson.com",i={CATEGORIES:"/products/category-list",PRODUCTS:"/products",PRODUCTS_BY_CATEGORY:"/products/category/",PRODUCT_BY_ID:"/products/",PRODUCTS_BY_SEARCH:"/products/search"},I={CART:"cart",WHISHLIST:"whishlist",THEME:"theme"};s.defaults.baseURL=A;function O(){return s.get(i.CATEGORIES).then(({data:t})=>t)}function f(){return s.get(i.PRODUCTS).then(({data:t})=>t)}function q(t){return s.get(`${i.PRODUCTS_BY_CATEGORY}${t}`).then(({data:e})=>e)}function D(t){return s.get(`${i.PRODUCT_BY_ID}${t}`).then(({data:e})=>e)}function F(t){return s.get(`${i.PRODUCTS_BY_SEARCH}?q=${t}`).then(({data:e})=>e)}function w(t){const o=["All",...t].map(c=>`<li class="categories__item">
        <button class="categories__btn" type="button">${c}</button>
      </li>`).join("");r.categoriesList.innerHTML=o;const n=document.querySelector(".categories__btn");n&&n.classList.add("categories__btn--active")}function l(t){const e=t.map(({id:o,thumbnail:n,title:c,brand:m,category:g,price:p})=>`<li class="products__item" data-id="${o}">
          <img class="products__image" src="${n}" alt="${c}" />
          <p class="products__title">${c}</p>
          <p class="products__brand">
            <span class="products__brand--bold">Brand: ${m}</span>
          </p>
          <p class="products__category">Category: ${g}</p>
          <p class="products__price">Price: ${p}$</p>
        </li>`).join("");r.productsList.insertAdjacentHTML("beforeend",e)}function M({id:t,thumbnail:e,title:o,brand:n,category:c,price:m,description:g,shippingInformation:p,returnPolicy:v,tags:y}){const P=y?y.map($=>`<li class="modal-product__tag">${$}</li>`).join(""):"",T=`<img class="modal-product__img" src="${e}" alt="${o}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${o}</p>
        <ul class="modal-product__tags">${P}</ul>
        <p class="modal-product__description">${g}</p>
        <p class="modal-product__shipping-information">Shipping: ${p}</p>
        <p class="modal-product__return-policy">Return Policy: ${v}</p>
        <p class="modal-product__price">Price: ${m}$</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`;r.modalProduct.innerHTML=T}function d(){r.notFound.classList.remove("not-found--visible")}function u(){r.notFound.classList.add("not-found--visible")}function C(){r.productsList.innerHTML=""}function H(t){try{const e=localStorage.getItem(t);return e?JSON.parse(e):null}catch(e){return console.log("Error geting data from local storage",e),null}}function L(){return H(I.CART)??[]}function U(t){return L(),L.includes(t)}let _=null;function Y(){O().then(t=>{w(t)}).catch(t=>{console.log("помилка запиту сторiнки home",t)}),f().then(({products:t})=>{l(t)}).catch(t=>{console.log("помилка рендеру продуктiв")})}function N(t){const e=t.target.closest(".categories__btn");if(console.log(e),!e)return;C();const o=r.categoriesList.querySelectorAll(".categories__btn");k(o,e,"categories__btn--active");const n=e.textContent.trim();console.log(n),n==="All"?f().then(({products:c})=>{console.log(c),d(),l(c)}).catch(c=>{console.log("помилка рендеру продуктiв")}):q(n).then(({products:c})=>{c.length>0?(d(),l(c)):u()}).catch(c=>{u(),console.log(c)})}function j(t){const e=t.target.closest(".products__item");if(!e)return;const o=Number(e.dataset.id);_=o,D(o).then(n=>{R(),M(n)}).catch(n=>{console.log(n)})}function G(t){t.preventDefault();const e=t.target.elements.searchValue.value.trim();if(console.log(e),e===""){B("Please enter search valid query","warning");return}F(e).then(({products:o})=>{C(),o.length>0?(l(o),d()):u()}).catch(o=>{console.log(o),u()})}function V(){r.searchForm.reset(),C(),f().then(({products:t})=>{l(t),d()}).catch(t=>{console.log("помилка рендеру продуктiв")})}function x(){_&&U(_)}document.addEventListener("DOMContentLoaded",Y);r.categoriesList.addEventListener("click",N);r.productsList.addEventListener("click",j);r.searchForm.addEventListener("submit",G);r.searchFormClearButton.addEventListener("click",V);r.AddToCartBtn.addEventListener("click",x);
//# sourceMappingURL=index.js.map
